name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: chmod
      run: chmod +x ./gradlew

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build -x test -Dspring.profiles.active=test --scan

    - name: check jar file
      run: ls -l ./build/libs

    - name: Make zip file
      run: zip -r ./deploy-jar.zip ./build/libs/DeployProject-0.0.1-SNAPSHOT.jar
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Upload to S3
      run: aws s3 cp --region us-east-2 ./deploy-jar.zip s3://jar-deploy-bucket/deploy-jar.zip

    - name: Code Deploy
      run: >
        aws deploy create-deployment --application-name GitCD 
        --deployment-config-name CodeDeployDefault.AllAtOnce
        --deployment-group-name GitCD-grp 
        --s3-location bucket=jar-deploy-bucket,bundleType=zip,key=deploy-jar.zip
